# Generated by Django 3.1.2 on 2020-11-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpoint',
            name='post_header',
            field=models.CharField(default='HEADER', max_length=250),
        ),
        migrations.AlterField(
            model_name='postpoint',
            name='post_point_text',
            field=models.TextField(verbose_name='Текст пункта поста'),
        ),
    ]
